### ISSUE TITLE
Transcoder runs, but nothing is happening

### ISSUE THREAD

**Issue by GRX** [pabloromeo/clusterplex#97] opened 2021-12-06 13:47 UTC
**Describe the bug**
It took me a while to get the setup running, debugigng on very low levels determined that the TMP path had a wrong permission which didn't show up in the console/log, generating errors when installing `binutils` to use `strings`. Therefor all my codecs where missing because the version couldn't be parsed. (This all just to inform you to perhaps add an extra check to see if `binutils` could be installed?).

Now that's tackled, it seems my stack is running and the transcoder is receiving transcode data from Plex (yay!).
However, it seems that nothing is happening when it starts to Transcode.

After loading the codecs, the container logs immediately get spammed with:
```
Output #0, dash, to 'dash':
  Metadata:
    encoder         : Lavf58.65.101
    Stream #0:0(eng): Video: h264, 1 reference frame, yuv420p(tv, bt709, progressive, left), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 11988 tbn (default)
    Metadata:
      encoder         : Lavc58.117.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 9299000/0/0 buffer size: 18598000 vbv_delay: N/A
    Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp, delay 1024, 130 kb/s (default)
    Metadata:
      encoder         : Lavc58.117.101 aac
Not writing 'clli' atom. No content light level info.
Not writing 'mdcv' atom. Missing mastering metadata.
Not writing 'clli' atom. No content light level info.
Not writing 'mdcv' atom. Missing mastering metadata.
[AVIOContext @ 0x7fb5254d3180] Statistics: 0 seeks, 1 writeouts
[dash @ 0x7fb537286040] Opening 'chunk-stream0-00001.m4s.tmp' for writing
[AVIOContext @ 0x7fb5254d3d40] Statistics: 0 seeks, 1 writeouts
[dash @ 0x7fb537286040] Opening 'chunk-stream1-00001.m4s.tmp' for writing
[AVIOContext @ 0x7fb522a99480] Statistics: 0 seeks, 1 writeouts
[dash @ 0x7fb537286040] Representation 0 media segment 2 written to: chunk-stream0-00001.m4s
[AVIOContext @ 0x7fb5254d3c00] Statistics: 0 seeks, 1 writeouts
[dash @ 0x7fb537286040] Representation 1 media segment 2 written to: chunk-stream1-00001.m4s
[dash @ 0x7fb537286040] Opening 'http://10.10.10.200:32400/video/:/transcode/session/uxsoberj00kw5lkbsikj8lbk/54eca413-dd02-4bf4-b625-7bfe598c72c7/manifest?X-Plex-Http-Pipeline=infinite' for writing
[tcp @ 0x7fb535c78240] Starting connection attempt to 10.10.10.200 port 32400
[tcp @ 0x7fb535c78240] Successfully connected to 10.10.10.200 port 32400
[AVIOContext @ 0x7fb5254d3c00] Statistics: 0 seeks, 1 writeouts
[dash @ 0x7fb537286040] Opening 'chunk-stream0-00002.m4s.tmp' for writing
[dash @ 0x7fb537286040] Opening 'chunk-stream1-00002.m4s.tmp' for writing
```
FYI: `10.10.10.200` is the local subnet IP of the server running Plex

This keeps running and after a while Plex console reports:
`Timed out waiting for segment.` and `Transcode runner appears to have died`

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Docker version: 20.10.7 (build f0df350)
 - Setup used: Linuxserver images with docker-mods (the example docker-compose.yml)

**Comment by pabloromeo** [comment] 2021-12-07 03:59
Hey!
Thanks for the info regarding TMP permissions, I'll make sure to add a comment to the readme.

So now, regarding your transcoding issue, it would appear that indeed transcoding begins correctly but Plex is never noticing the new segments being written.
What's your network share configuration like regarding the Transcoding Temp location? Meaning, both /tmp and the transcoding directory have to be network shares of some kind for the content to be accesible to both and mapped to the same locations on both PMS and the Worker.

You can also manually monitor that path and see if the worker is indeed creating the segments in the proper location.

There may also be useful information on the logs on Plex's side, with some info as to why it's not finding the segments in the expected location.

**Comment by GRX** [comment] 2021-12-11 20:42
Thank you for replying, sorry that it took so long for me to respond.

The `plex` service in my yml has the following volumes:
```
volumes:
      - /mnt/cluster/dockerdata/mediacenter/plex-lb/config:/config
      - /mnt/cloud/gdrive/backups/plex:/backups
      - /mnt/cluster/dockerdata/mediacenter/plex-lb/tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
```

The `plex-worker` service in my yml has the following volumes:
```
volumes:
      - /mnt/cluster/dockerdata/mediacenter/plex-lb/codecs:/codecs
      - /mnt/cluster/dockerdata/mediacenter/plex-lb/tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
```

I redacted the movie/show mounts from above.

In the directory I can see the transcode session, plus the transcoded files:
![image](https://user-images.githubusercontent.com/14363136/145691039-3ce64a16-eefa-4b04-8ba5-6a22601502c1.png)

**Comment by pabloromeo** [comment] 2021-12-13 16:28
Ah I see. And I'm assuming the path configured for the transcoder is indeed a subdirectory of that shared /tmp:
![image](https://user-images.githubusercontent.com/41338020/145849567-f8c29954-e8a3-4bb3-8241-6f51afdfedb1.png)

So, it would appear that the transcoder is indeed working as expected, given that transcoding begins, chunks get generated, and the progress is notified back to your PMS (through the progressUrl you see there in the logs).
It sounds like there might be something happenning on the PMS side of things, were it's either not finding the chunks where it expects them to be or doesn't have access.

Have you checked the PMS logs, such as in the Console within the UI, to see if Plex is throwing any errors there? You might want to also temporarily enable debug and/or verbose logging, to view more details about what it's doing while attempting to play back content.

**Comment by Manaconda** [comment] 2022-01-10 16:33
Hi, did you ever get to the bottom of this? I'm having exactly the same issue.

I'm using gluster for my shared storage.

In addition to the behaviour described by @GRX I've also noticed warnings in the PMS console

`[Transcode/1rxv04er7g3yqsih7w173spe] Timed out waiting for segment.  `

These repeat every so often

Along with the error

`[Transcoder] [http @ 0x7f23aa37b2c0] URL read error: End of file`

**Comment by pabloromeo** [comment] 2022-01-10 19:01
Hey!
I never heard back from GRX. I haven't been able to reproduce the errors. I did recommend reviewing the config, making sure /tmp was shared, mounted, and configured in PMS correctly, as well as a few extra settings that might help.
Ultimately those errors are thrown by Plex itself, meaning it's not ClusterPlex's code. Reviewing detailed logs sometimes sheds like on these sorts of issues.
For example, what the worker does is change the progressUrl used to report back to PMS the progress. That might be causing trouble if not configured correctly in the worker.
Also if transcoding is indeed happenning on the worker and is available to the PMS in the same exact path then we need to enable debug logging on PMS to see if any additional info comes up there.

**Comment by Manaconda** [comment] 2022-01-10 21:00
Thanks for getting back to me.  I've had another play with it just now and everything is working !  

The fix in my case was was the "List of IP addresses and networks that are allowed without auth" mentioned above.  I had tried this previously but had forgotten that every time the stack came up the subnet that swarm was using was changing.  It may not be ideal but I've just added 10.0.0.0/8 to the allow list and playback is working perfectly.

Thanks again.

**Comment by pabloromeo** [comment] 2022-01-10 22:01
Ah, I see, so my suspicion about the "List of IP Addresses..." causing it to fail wasn't too far off.
Yes I have a similar setting in my cluster, I just wasn't certain that it was indeed necessary since I've had that set up that way for quite a while.e
Thanks so much for the feedback! 👍 I'll add it to the README instructions as well, and close this issue.

**Comment by pabloromeo** [comment] 2022-01-10 22:50
Improved documentation in #109

**Closed by pabloromeo** 2022-01-10 22:50 UTC
Labels: bug
